### PR TITLE
Add lesson skeleton

### PR DESCRIPTION
**Pull request by karawoo**
I added the lesson.html and lesson.css from the old software carpentry `bc` repo and created an `index.md` file for a table of contents. We'll be able to have nicely formatted pages this way, but I think it requires a little extra fiddling with knitr to get it to create markdown files that render properly (e.g. [raw](https://raw.githubusercontent.com/karawoo/2015-01-05-wise-umich/gh-pages/novice/shell-datamgmt/01-exploring.md) and [rendered](http://karawoo.com/2015-01-05-wise-umich/novice/shell-datamgmt/01-exploring.html)). So other suggestions are welcome. I haven't had time to look at Software Carpentry's R lesson repositories to see what they do. Right now the index points to a ggplot page that doesn't exist.

### CODE REVIEW

**Comment by kbroman** [comment]
I'm happy for you to merge it.

I find the s/w carpentry repository layouts a bit confusing.
For example, if I want to add a data file or notes for a lesson, where should I put such?

**Comment by karawoo** [comment]
They're confusing for me too, especially now that the lessons are being managed separately from the websites. This PR creates a folder called `syllabus` where I thought we could put lesson notes. If you save them as markdown files they'll appear at http://karawoo.github.io/syllabus/filename.html, I think. We could put data in here too, for lack of any better ideas. If this seems like a good enough approach then I will go ahead and merge. I'm traveling so might be slow.

**Comment by kbroman** [comment]
Okay; sounds good. I like separating the source material and the website; I'd just do separate branches of a common repository. Is that what SWC does?

**Comment by karawoo** [comment]
I think the SWC website repo now doesn't contain any lessons at all, but I like having my lessons available on there so I can have them open in a browser on my tablet while I'm teaching.

**Pull request merged**
