### PR TITLE
Add git stuff 

### PR DESCRIPTION
**Pull request by kbroman**
Taken from https://github.com/karawoo/2015-01-05-wise-umich/tree/gh-pages/novice/git

First session: `git-00-intro` & `git-01-backup`

Second session: `git-02-collab` & `git-03-conflict`

### CODE REVIEW

**Comment by karawoo** [comment]
Thanks for adding this @kbroman. Are you planning to teach the Wolfman & Dracula storyline for git local, or adapt the lesson to teach the same topics but using the gapminder data/scripts/etc.?

**Comment by kbroman** [comment]
I'd prefer to adapt to use the gapminder data and scripts. But that shift would be more work for you, in the second session on collaboration/github.

**Comment by karawoo** [comment]
That's fine, I would prefer to adapt it too.

**Comment by karawoo** [comment]
Did you want to merge this right away or are you planning to modify the lessons first? Either one is fine by me.

**Comment by kbroman** [comment]
No need to wait; I made it a pull request just so there's a more clear record.

**Comment by kbroman** [comment]
Then I closed it without merging. Brilliant.

**Comment by karawoo** [comment]
I've made pull requests for myself to merge on my own projects, but I've
never rejected one of my own pull requests. You are a harsh code reviewer,
Karl. ;)

**Pull request merged**
