### PR TITLE
Compile lessons

### PR DESCRIPTION
**Pull request by kbroman**
See [this comment](https://github.com/karawoo/2015-04-27-wsu/issues/24#issuecomment-95379986) on [issue #24](https://github.com/karawoo/2015-04-27-wsu/issues/24).

Test this out before merging. I've only tested the `ggplot2.Rmd` lesson so far.

### CODE REVIEW

**Comment by karawoo** [comment]
Thanks Karl, I will test this out tomorrow morning. Should `make preview` compile all the lessons, or is it best to do them individually?

**Comment by kbroman** [comment]
Yes `make preview` does work to compile all lessons.

**Comment by kbroman** [comment]
I added a some more stuff to this pull request:
- Add the compiled lessons
- Made small changes git and R-intro lessons, to eliminate duplicate titles in the html files.

**Comment by kbroman** [comment]
This works fine; I'm going to go ahead and merge.

**Pull request merged**
